### PR TITLE
fix #212 remove default chain param value

### LINKED ISSUE #212: read command requires specifying a chain to query mainnet tables
Using the latest version
```bash
$ tableland --version
4.0.4
```
It doesn't work to query a table from a non-testnet chain
```
$ tableland read "select * from rig_attributes_42161_15 limit 1"
running read statement: executing read-query: parsing result to json: executing query: no such table: rig_attributes_42161_15
```
Unless a mainnet chain is specified (doesn't have to be the chain that the table lives on, any mainnet chain works)
```
$ tableland read "select * from rig_attributes_42161_15 limit 1" --chain mainnet
{
  meta: { duration: 751.7410420179367 },
  success: true,
  results: [
    {
      display_type: 'string',
      rig_id: 1,
      trait_type: 'VIN',
      value: 'e9e7caceadc2e5fb4fcbd42c0a6ed0097c709aa01888f70e6d924439ec119ca3'
    }
  ]
}
```
 Feels a bit unintuitive to me and I think this is a regression/undocumented change from the v3 cli? I would expect it to either infer that from the tablenames or that I would have to specify the tableland network I want to target, like `--network testnets` to be consistent with the validator api

### PR DESCRIPTION
**Pull request by joewagner**
## Context

Fix for #212 
The read command was using the SDK's `Database.readOnly` function, which requires a chain.  Using the default Database constructor removes this requirement.
related: https://github.com/tablelandnetwork/js-tableland/issues/375

## Details

Because we had a default value for the `chain` param, read commands that run against the mainnets would fail with a "no such table" message unless the caller specifies a mainnet chain.  This is somewhat confusing, and not really necessary because the chain can (almost always?) be derived from the query statement.

Some notes on the changes here:
 - removes the default value for the chain param.
 - because we are changing the default behaviour I believe we will need to bump a major version for this change.

### CODE REVIEW

File: src/lib/commandSetup.ts [hunk 1]
```diff
@@ -70,74 +68,70 @@ export class Connections {
...
-      readOnly && !baseUrl
-        ? Database.readOnly(chain)
-        : new Database({
-            signer,
-            baseUrl,
-          });
+    this._database = new Database({
+      // both of these props might be undefined
+      signer: this._signer,
+      baseUrl,
```
Comment (joewagner) [inline src/lib/commandSetup.ts:121]: This is one of the potential down sides to the new approach here.
These values might be `undefined`, so when doing a read-through devs could be a little confused.  My hope is that using comments will solve this.

File: test/create.test.ts [hunk 2]
```diff
@@ -27,6 +27,24 @@ describe("commands/create", function () {
     );
   });
 
+  test("throws if chain not provided", async function () {
```
Comment (joewagner) [inline test/create.test.ts:30]: We had a test for "no chain". I added one, so now we have "no chain" and "bad chain".

File: test/read.test.ts [hunk 3]
```diff
@@ -16,18 +16,22 @@ describe("commands/read", function () {
     restore();
   });
 
-  test("throws with invalid chain", async function () {
+  test("throws with invalid table name", async function () {
```
Comment (joewagner) [inline test/read.test.ts:19]: `read` no longer uses the `--chain` flag, so I repurposed this test to check the table name validation.

File: test/read.test.ts [hunk 4]
```diff
@@ -38,7 +42,13 @@ describe("commands/read", function () {
 
   test("throws with missing file", async function () {
     const consoleError = spy(console, "error");
-    await yargs(["read", "--file", "missing.sql", "--chain", "local-tableland"])
+    await yargs([
+      "read",
+      "--file",
+      "missing.sql",
+      "--baseUrl",
```
Comment (joewagner) [inline test/read.test.ts:49]: I included the baseUrl in some of these tests because I wanted to make sure that actual thing under test was the cause of the error without worrying about the order of command validations.

File: test/shell.test.ts [hunk 5]
```diff
@@ -49,11 +49,24 @@ describe("commands/shell", function () {
     );
   });
 
-  test("Shell throws without network", async function () {
```
Comment (joewagner) [inline test/shell.test.ts:52]: This is kind of a nit.  The term network seems ambiguous, and we are testing the `--chain` flag.

**Review by joewagner — COMMENTED** [review]
@carsonfarmer The original issue is fixed, but I ended up going down a bit of a rabbit hole and doing some refactoring.
It would be awesome if you can look this over when you get a free cycle. Definitely push back on anything in here that doesn't make sense.

**Review by datadanne — COMMENTED** [review]
Nice! I played with a build from this branch locally and it works great. I even like chain not having a default for any command, imo it makes sense that you always have to specify it when you run a command that is targeting a specific chain

File: src/lib/commandSetup.ts [hunk 6]
```diff
@@ -70,74 +68,70 @@ export class Connections {
...
 
-  async prepare(
-    argv: GlobalOptions,
-    options: { readOnly: boolean } = { readOnly: false }
-  ) {
+  // Once a command is issued we want to collect the args and options and
+  // "prepare" all of the underlying interfaces, e.g. validator, signer, database, etc...
+  // The strategy we are employing here boils down to, "setup everything we can with what we are given"
+  // Then the command handler will have everything it needs as long as it is requiring the correct
+  // args.
```
[the remark this answers is not in the document]
Comment (awmuncy) [reply src/lib/commandSetup.ts:81]: The refactor looks excellent to me, much easier to read about.

File: src/cli.ts [hunk 7]
```diff
@@ -60,7 +60,6 @@ const _argv = yargs(hideBin(process.argv))
     alias: "c",
     type: "string",
     description: "The EVM chain to target",
-    default: "maticmum",
```
[the remark this answers is not in the document]
Comment (awmuncy) [reply src/cli.ts:63]: Major? From 4.x to 5.x?

File: src/commands/shell.ts [hunk 8]
```diff
@@ -160,6 +160,11 @@ export const builder: CommandBuilder<{}, Options> = (yargs) =>
 
 export const handler = async (argv: Arguments<Options>): Promise<void> => {
   try {
+    const { chain } = argv;
+    if (!chain) {
```
[the remark this answers is not in the document]
Comment (awmuncy) [reply src/commands/shell.ts:164]: Is there an alternative?

File: test/create.test.ts (hunk 2 above)
Comment (awmuncy) [reply test/create.test.ts:30]: Great!

File: test/shell.test.ts (hunk 5 above)
Comment (awmuncy) [reply test/shell.test.ts:52]: Nits are good, this is a good one.

**Review by awmuncy — APPROVED** [review]
This looks great! One thing I would say is if we're going to do a major version bump to 5.x, we could probably wait until this PR https://github.com/tablelandnetwork/js-tableland-cli/pull/219 is merged as well, because it too will have some backward incompatible changes.

File: src/cli.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (joewagner) [reply src/cli.ts:63]: I think so, does that make sense to you?

**Comment by joewagner** [comment]
> This looks great! One thing I would say is if we're going to do a major version bump to 5.x, we could probably wait until this PR #219 is merged as well, because it too will have some backward incompatible changes.

Sounds good to me!  Should we merge this to main and wait to publish, or create a v5 branch to hold the combined changes?

**Comment by awmuncy** [comment]
> > This looks great! One thing I would say is if we're going to do a major version bump to 5.x, we could probably wait until this PR #219 is merged as well, because it too will have some backward incompatible changes.
> 
> Sounds good to me! Should we merge this to main and wait to publish, or create a v5 branch to hold the combined changes?

Yes, I think that's a good idea.
