### PR TITLE
fix: allow insert with subselect

### LINKED ISSUE #392: [JSTC-34] Insert + flat select fails if primary key not specified
## Summary

I have a `main` table (including an `id INTEGER PRIMARY KEY`, i.e., auto-incrementing) and an `admin` table. The `main` stores misc. data, and `admin` stores provisioned admin addresses. Only if a value exists in `admin` can an insert happen with `main`. I would like to conditionally insert into `main`, but the parser fails if I try to make an INSERT with a flat SELECT *without* specifying the `id` column. In other words, `id` is required, but since I want to auto-increment this column, this is not ideal.

## Steps to reproduce

I have done the following table setup using the CLI with LT:

* `create table main (id integer primary key, data text);`
* `create table admin (id integer primary key, address text);`
* `insert into admin_31337_3 (address) values ('0xabcd');`

From here, I want to lookup a value (`0xabcd`) in `admin` and only insert data (e.g., a `'test'` string) in `main` if the `admin` value exists. I *cannot* do that with the following query, which breaks my desire to auto-increment `main`:

* `insert into main_31337_2 (data) select 'test' from admin_31337_3 where address = '0xabcd';`

Instead, I *have to* specify the `id` column for `main`—this *does* work but again, isn't ideal:

* `insert into main_31337_2 (id, data) select 1, 'test' from admin_31337_3 where address = '0xabcd';`

### Error

For context, upon trying to insert into main *without* the `id` column, the following is logged via the CLI and complains about the `main` table having 2 columns but only 1 value was supplied: 

```
Error: ALL_ERROR: db query execution failed (code: SQLITE_table main_31337_6 has 2 columns but 1 values were supplied, msg: table main_31337_6 has 2 columns but 1 values were supplied)
    at errorWithCause (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/lowlevel.js:103:12)
    at Statement.all (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/statement.js:90:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fireFullQuery (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:46:30)
    at async shellYeah (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:113:17) {
  [cause]: Error: db query execution failed (code: SQLITE_table main_31337_6 has 2 columns but 1 values were supplied, msg: table main_31337_6 has 2 columns but 1 values were supplied)
      at errorWithHint (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/lowlevel.js:119:16)
      at Statement.all (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/statement.js:89:26)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async fireFullQuery (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:46:30)
      at async shellYeah (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:113:17) {
    [cause]: Error: db query execution failed (code: SQLITE_table main_31337_6 has 2 columns but 1 values were supplied, msg: table main_31337_6 has 2 columns but 1 values were supplied)
        at Object.wait (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/registry/utils.js:50:19)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async checkWait (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/helpers/config.js:5:24)
        at async Statement._Statement_waitExec (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/statement.js:196:12)
        at async Statement.all (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/node_modules/@tableland/sdk/dist/esm/statement.js:84:39)
        at async fireFullQuery (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:46:30)
        at async shellYeah (file:///Users/dtb/.nvm/versions/node/v18.12.1/lib/node_modules/@tableland/cli/dist/commands/shell.js:113:17)
  }
```

## Expectation

I'd expect that since I can typically make a query that does not specify the `id` column, such as doing `insert into main_31337_2 (data) values ('test')`on its own, it should also work with a INSERT + flat SELECT.

<sub>From [SyncLinear.com](https://synclinear.com) | [JSTC-34](https://linear.app/tableland/issue/JSTC-34/insert-flat-select-fails-if-primary-key-not-specified)</sub>

### PR DESCRIPTION
**Pull request by dtbuchholz**
## Summary

The fix is handled in the SDK to allow an INSERT with a subselect statement. There is slight logic _removal_ here, which was previously throwing an error due to the CLI thinking the mutating query is affecting more than one table. Closes #392.

## Details

There is an open PR in the SDK ([here](https://github.com/tablelandnetwork/js-tableland/pull/562)) that will resolve the issue, which was due to the CLI's usage of the `batch` method that wasn't allowing for mutating queries with subselects. That PR must be merged first.

Additionally, the CLI had the following code, which was deemed unnecessary as the SDK `batch` method will throw the error `parsing query: queries are referencing two distinct tables`; thus, this is no longer needed:

```ts
if (norm.tables.length > 1) {
  throw new Error(
    "cannot normalize if single query affects more then one table"
  );
}
```

Note: if you pass a single statement with multiple tables (e.g., `INSERT INTO table1 ...; INSERT INTO table2 ...`), the CLI actually splits these into separate runnables. This is noted because it's somewhat related to logic removed above but, again, the SDK should bubble up the error noted above.

## How it was tested

Added a test while setting up a symlink to the SDK PR noted above: `passes with insert and subselect`

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by dtbuchholz** [comment]
note: if the `"cannot normalize if single query affects more then one table"` error should be kept, i can rework things here. my thinking was that it'd end up duplicating the logic [from the SDK](https://github.com/tablelandnetwork/js-tableland/blob/e3902b7715c1029ab29751622b548303418c01d6/src/database.ts#L237).

File: src/commands/write.ts [hunk 1]
```diff
@@ -97,12 +97,6 @@ export const handler = async (argv: Arguments<Options>): Promise<void> => {
         normalized.statements.map(async function (stmt) {
           // re-normalize so we can be sure we've isolated each statement and it's tableId
           const norm = await normalize(stmt);
-          /* c8 ignore next 5 */
-          if (norm.tables.length > 1) {
-            throw new Error(
-              "cannot normalize if single query affects more then one table"
-            );
-          }
           const { tableId } = await globalThis.sqlparser.validateTableName(
```
Comment (awmuncy) [inline src/commands/write.ts:100]: Before this change, the array returned from `normalize()` consisted of only a single item at this point in execution. Now, there could be statements where there first tableId return from normalize may not be the tableId being mutated. That seems wrong, somehow. 

This might be moot though, I don't see the tableId being used later, but it seems like it could trip someone up later.

**Comment by awmuncy** [comment]
It also looks like the test for inserts with subselects is failing in node 18 for some reason.

File: src/commands/write.ts (hunk 1 above)
Comment (dtbuchholz) [reply src/commands/write.ts:100]: hmm yeah, the regex logic i had to add to the SDK had to deal with this—i.e., the `tableId`s returned for a INSERT + subselect included both table IDs, even though there was only one table being mutated. feels like the sqlparser should handle these types of things?

**Comment by dtbuchholz** [comment]
> It also looks like the test for inserts with subselects is failing in node 18 for some reason.

kk will take a look out once the SDK [branch](https://github.com/tablelandnetwork/js-tableland/pull/562) gets merged—that's probably why but will double check.

File: src/commands/write.ts (hunk 1 above)
Comment (dtbuchholz) [reply src/commands/write.ts:100]: e.g., i feel like the parser should do the regex-type logic and return `tables: { read: [...], write: [...] }` (unrelated: sorta like how the aliases config file sets things up, in a way)

**Comment by dtbuchholz** [comment]
@awmuncy mind giving me a 👍 on this? should work now with the latest SDK

**Review by awmuncy — APPROVED** [review]
Looks good!
