### PR TITLE
fix #213 use default provider when url not given

### LINKED ISSUE #213: receipt command is broken, returns ethers error "could not detect network" NETWORK_ERROR
The `receipt` command doesn't work. I've tried both with mumbai transactions and mainnet transactions and both are broken. 
```
$ tableland version
4.0.4
```
Example receipt command that doesn't work
```
$ tableland receipt 0xe2c275e1d9bb83443e9046bf322efbd19e1fac70a26ed565f7449c9b9f4284be --chain mainnet --k 0x00000000000000000000000000000000000000000000000000000000deadbeef
could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.7.2)
```

### PR DESCRIPTION
**Pull request by joewagner**
The `getWalletWithProvider` helper function was never using the default provider which was causing an unexpected error in calls to `receipt` if a provider url wasn't given.

@datadanne Thanks for finding this issue.

### CODE REVIEW

File: src/utils.ts [hunk 1]
```diff
@@ -76,8 +85,15 @@ export async function getWalletWithProvider({
     throw new Error("unable to create ETH API provider");
   }
 
-  if ((await provider.getNetwork()).chainId !== network.chainId) {
-    throw new Error("Provider / chain mismatch.");
+  let providerChainId: number | undefined;
+  try {
+    providerChainId = (await provider.getNetwork()).chainId;
+  } catch (err) {
+    throw new Error("cannot determine provider chain ID");
```
Comment (joewagner) [inline src/utils.ts:92]: I added this try-catch-throw in hopes users will have an easier time determining why a call failed.

**Review by carsonfarmer — APPROVED** [review]
Nice quick (and correct) fix here @joewagner. Let's get a patch release of this out asap.
